import {
  
    StyleSheet,
  } from 'react-native';

const styles = StyleSheet.create({
    mainContainer: {
      flex: 1,
      backgroundColor: '#15616d',
      alignItems: 'center',
    },
    myWallet: {
      color: 'white',
      fontSize: 25,
      marginTop: 10,
    },
    innerContainer: {
      backgroundColor: '#F8F8F8',
      borderTopRightRadius: 30,
      borderTopLeftRadius: 30,
    },
    ticketCard: {
      width: 320,
      height: 90,
      backgroundColor: '#15616d',
      borderRadius: 10,
      margin: 25,
    },
    firstDot: {
      position: 'absolute',
      width: 15,
      height: 15,
      borderRadius: 25,
      left: -8,
      top: 36,
      backgroundColor: 'white',
    },
    secondDot: {
      position: 'absolute',
      right: -8,
      width: 15,
      height: 15,
      borderRadius: 25,
      top: 36,
      backgroundColor: 'white',
    },
    walletBalanceText: {
      color: 'white',
      marginLeft: 10,
      fontSize: 20,
      bottom: 5,
      fontWeight: '200',
    },
    circle: {
      width: 20,
      height: 20,
      borderRadius: 30,
      backgroundColor: '#c0c0c0',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 40,
      marginLeft: 20,
    },
    cancelText: {
      fontSize: 14,
      color: 'lightgrey',
      fontWeight: '500',
    },
    tarnscationHistory: {
      color: 'black',
      textAlign: 'center',
      margin: 15,
      left: 10,
      fontWeight: '500',
    },
    borderOfTranscationHistory: {
      borderColor: 'black',
      borderWidth: 0.5,
      top: 30,
      borderRadius: 5,
      marginLeft: 20,
      marginRight: 20,
      height: 50,
      marginBottom: 150,
      flexDirection: 'row',
    },
    backgrounOfAdd: {
      backgroundColor: 'rgba(235,235,235,1.2)',
      height: 40,
      width: '90%',
      top: 10,
      justifyContent: 'center',
      alignSelf: 'center',
      borderRadius: 5,
    },
    backgrounOfTextInput: {
      backgroundColor: 'rgba(229,229,229,0.55)',
      height: 40,
      width: '90%',
      top: 40,
      justifyContent: 'center',
      alignSelf: 'center',
      borderRadius: 5,
    },
    backgrounOfAmounts: {
      display: 'flex',
      flexDirection: 'row',
      borderWidth: 0.8,
      left: 15,
      borderRadius: 4,
      width: '20%',
      height: '100%',
    },
    borderLine: {
      height: 1.5,
      backgroundColor: 'black',
      marginTop: 10,
      marginLeft: 90,
      marginRight: 80,
    },
    addMoneyText: {
      textAlign: 'center',
      marginTop: 20,
      color: 'black',
      fontSize: 20,
      fontWeight: '500',
    },
    mainContainerOfAddMoney: {
      backgroundColor: '#ffffff',
      height: 100,
      marginTop: 20,
      width: 300,
      height: 300,
      alignSelf: 'center',
      borderRadius: 10,
      elevation: 1,
      shadowColor: '#ccc',
      shadowOffset: {width: -1},
      shadowOpacity: 0.5,
      shadowRadius: 0.9,
      zIndex: 5,
    },
    containerOfRecharge: {
      marginTop: 20,
      backgroundColor: '#c0c0c0',
      width: '100%',
      height: 50,
      flexDirection: 'row',
      justifyContent: 'center',
    },
    backgrounOfOnlineRecharge: {
      backgroundColor: '#15616d',
      right: 35,
      margin: 6,
      borderRadius: 10,
      width: '45%',
    },
    textOfOnlineRecharge: {
      color: 'white',
      alignSelf: 'center',
      textAlign: 'center',
      justifyContent: 'center',
      marginTop: 8,
      letterSpacing: 0.2,
    },
    textOfAdd:{
      marginTop: 37,
      fontSize: 18,
      marginLeft: 10,
      color: '#15616d',
      fontWeight: '500',
    },
    textOfZero:{
      marginLeft: 10,
      marginTop: 28,
      fontSize: 30,
      color: 'grey',
      fontWeight: 'bold',
    }
  });

  export default styles;
  